[package]
name = "utokio"
version = "0.1.0"
edition.workspace = true
rust-version.workspace = true

[dependencies]
tokio = { workspace = true, features = ["full"] }
mini-redis = { workspace = true, features = [] }
