[workspace]
resolver = "2"
members = [
    "essentia",
    "uactix_web",
    "uaxum",
    "uplotters",
    "upolars",
    "urayon",
    "ureqwest",
    "usqlx",
    "usurrealdb",
    "utokio"
]

[workspace.package]
edition = "2024"
rust-version = "1.91.0"

[workspace.dependencies]
tokio       = { default-features = false, version = "1.48.0" }
rayon       = { default-features = false, version = "1.11.0" }
reqwest     = { default-features = false, version = "0.12.24" }
sqlx        = { default-features = false, version = "0.8.6" }
surrealdb   = { default-features = false, version = "2.3.10" }
polars      = { default-features = false, version = "0.52.0" }
plotters    = { default-features = false, version = "0.3.7" }
axum        = { default-features = false, version = "0.8.6" }
actix-web   = { default-features = false, version = "4.11.0" }

serde       = { default-features = false, version = "1.0.228" }
serde_json  = { default-features = false, version = "1.0.145" }
walkdir     = { default-features = false, version = "2.5.0" }
chrono      = { default-features = false, version = "0.4.42" }
