[package]
name = "uaxum"
version = "0.1.0"
edition.workspace = true
rust-version.workspace = true

[dependencies]
axum = { workspace = true, features = ["tokio", "http2"] }
tokio = { workspace = true, features = ["full"] }
reqwest = { workspace = true, features = [] }
