[package]
name = "usqlx"
version = "0.1.0"
edition.workspace = true
rust-version.workspace = true

[dependencies]
tokio = { workspace = true, features = ["full"] }
sqlx = { workspace = true, features = ["runtime-tokio"] }
sqlx-macros = { workspace = true, features = [] }
